// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD475Rs62ktrazu4iL7URJdOmej4uhBEsY',
    appId: '1:675136926988:android:31d68bdea0343659d10529',
    messagingSenderId: '675136926988',
    projectId: 'fitting-room-manager',
    databaseURL: 'https://fitting-room-manager-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fitting-room-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSv-n2zgoDEtbiz1BYaQ7Np_ljzh7mU7U',
    appId: '1:675136926988:ios:b83fd13e543d03e9d10529',
    messagingSenderId: '675136926988',
    projectId: 'fitting-room-manager',
    databaseURL: 'https://fitting-room-manager-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fitting-room-manager.appspot.com',
    iosClientId: '675136926988-rs7m5vvo4h02tjvm3b6gvq9vqrqvuof0.apps.googleusercontent.com',
    iosBundleId: 'com.example.frControl',
  );
}
